### ISSUE TITLE
GameJolt_Scores_Add "Extra Data" issue

### ISSUE THREAD

**Issue by lukefruin** [YoYoGames/GMEXT-GameJolt#2]
In Scr_GameJolt_UserFunctions, line 172, the url is not passed into Scr_GameJolt_Parameters as an argument causing a DoAdd error due to an undefined value. The error only occurs when using "Extra Data".
Fixed easily by passing the url into the function as argument 0.

**Comment by jzavala-YYG** [comment]
Hi @lukefruin, thanks for report this issue. I located the same problem on GameJolt_Scores_Add_Guest() too, fixed on both functions.
